### ISSUE TITLE
WordPress.Org : plugin no more available

### ISSUE THREAD

**Issue by Draky50110** [patrickrobrecht/extended-evaluation-for-statify#23]
Hello.

This plugin is no more listed in official repo : This plugin was closed on February 26, 2018 and is no longer available for download. Reason: Licensing/Trademark Violation.

Is it normal ?

Will it change ?

Thanks

**Comment by patrickrobrecht** [comment]
Hello,
a new release is in development and can be tested: https://github.com/patrickrobrecht/extended-evaluation-for-statify/releases/tag/v2.5.0-rc.1.

The reason the plugin was closed is that the charts library is not compatible with the GPL. Version 2.5.0 will be compatible with the GPL and it's intended to publish the plugin in the official plugin repository on wordpress.org again.

**Comment by websupporter** [comment]
will give it a test and feedback by tomorrow.

**Comment by patrickrobrecht** [comment]
It's available on [wordpress.org](https://wordpress.org/plugins/extended-evaluation-for-statify/) again.
