### ISSUE TITLE
Tracking outbound links

### ISSUE THREAD

**Issue by knodderdachs** [patrickrobrecht/extended-evaluation-for-statify#35]
Hi,

would it be possible to include a function to record the number of clicks on outbound links (e.g. social media profiles) in the statistics?

ATB
Torsten

**Comment by patrickrobrecht** [comment]
As *Statify - Extended Evaluation* does not collect any data, but is just an extension for Statify which provides additional evaluation of the data from the Statify table, I won't implement this feature.
